<a href="https://colab.research.google.com/github/Hui0223/pytorch-deep-learning/blob/main/00_jh_pytorch_fundamentals_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00.PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

scalar: 0 dim
vector: 1 dim
matrix: 2 dim
tensor: 3+ dim

Why random tensors?

A:随机张量很重要，因为许多神经网络的学习方式是它们从充满随机数的张量开始，然后调整这些随机数以更好的表示数据。
从随机数开始 -> 查看数据 -> 更新随机数 -> 查看数据 -> 更新随机数


In [15]:
#craete a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4053, 0.2544, 0.0552, 0.7220],
        [0.6252, 0.8752, 0.5765, 0.1208],
        [0.8614, 0.3394, 0.7744, 0.9249]])

In [16]:
random_tensor.ndim

2

In [17]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [18]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

Create a range of tensors an tensors-like

In [22]:
#Use torch.range()
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
#create tensors like
ten_zeros = torch.zeros_like(input=ones)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Tensor datatypes:

1.张量不是正确的数据
2.张量形状不正确
3.张量不在正确的设备上

In [24]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=None,# what datatype is the tensor (e.g. float32 or float16)
                device=None, # what device is your tensor on
                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
flocat_16_tensor = float_32_tensor.type(torch.float16)
flocat_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
flocat_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device -> default is "cpu"

In [30]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6597, 0.5411, 0.5617, 0.6029],
        [0.6478, 0.0307, 0.2951, 0.8603],
        [0.3560, 0.5184, 0.6256, 0.8660]])

In [31]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6597, 0.5411, 0.5617, 0.6029],
        [0.6478, 0.0307, 0.2951, 0.8603],
        [0.3560, 0.5184, 0.6256, 0.8660]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors(tensor operations)

Tensor operations include:

*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication







In [32]:
#create a tensor and add 10 to it
aa = torch.tensor([1,2,3])
aa + 10


tensor([11, 12, 13])

In [33]:
aa*10
aa

tensor([1, 2, 3])

In [34]:
torch.mul(aa,10)

tensor([10, 20, 30])

In [35]:
torch.add(aa,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product 点积）

两个规则：

1.内部尺寸必须匹配

(3,2)@(2,3) = (3,3)

(2,3)@(3,2) = (2,2)

2.结果矩阵的形状具有外部尺寸

In [36]:
#Element wise multiplication
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [37]:
a * a

tensor([1, 4, 9])

In [38]:
%%time
torch.matmul(a,a)

CPU times: user 629 µs, sys: 97 µs, total: 726 µs
Wall time: 15.9 ms


tensor(14)

In [39]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6649, 0.3083],
        [0.6715, 0.5709]])

One of the most common errors in deep learning : shape errors

In [40]:

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [41]:
# 转置，当内部尺寸不匹配的时候，可以进行转置
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

Finding the min,max,mean,sum, etc (tensor aggragation)

In [42]:
#create a tensor
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [43]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [44]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [45]:
#torch.mean()要求数据是float32,不然会报错
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [46]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

找到最大最小值的位置

In [47]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
x.argmin()

tensor(0)

In [49]:
x[1]

tensor(10)

In [50]:
x.argmax()

tensor(9)

In [51]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Reshaping, stacking, squeezing and unsqueezing tensors

1. Reshaping - reshapes an input tensor to a defined shape

2. View - return a view of an input tensor of certain shape but keep the same memory as the original tensors

3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

4. Squeeze -removes all 1 dimensions from a tensor

5. Unsqueeze - add a 1 dimension to a target tensor

6. Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [52]:
#create a tensor
import torch
x = torch.arange(1.,21.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]),
 torch.Size([20]))

In [53]:
# add an extra dimension 把原有tensor里所有元素重新塑形编排，数量要保持和原tensor 20个元素一致，可以是1*20/2*10/4*5/5*4/10*2/20*1
x_reshaped = x.reshape(1,20)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 torch.Size([1, 20]))

In [54]:
x_reshaped = x.reshape(2,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]]),
 torch.Size([2, 10]))

In [55]:
x_reshaped = x.reshape(4,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20.]]),
 torch.Size([4, 5]))

In [56]:
x_reshaped = x.reshape(5,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.]]),
 torch.Size([5, 4]))

In [57]:
x_reshaped = x.reshape(10,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.],
         [13., 14.],
         [15., 16.],
         [17., 18.],
         [19., 20.]]),
 torch.Size([10, 2]))

In [58]:
#change the view
z = x.view(1,20)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 torch.Size([1, 20]))

In [59]:
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,5] = 5
z,x

(tensor([[ 1.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]))

In [60]:
# Stack tensors on top of each other
import torch
x = torch.arange(1.,9.)
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.]]),
 torch.Size([4, 8]))

In [61]:
import torch
x = torch.arange(1.,9.)
# x is a 1D tensor, so valid dimensions for stacking are 0 or 1.
# dim=0 will stack along a new first dimension, resulting in shape (num_tensors, x.size()).
# dim=1 will stack along a new last dimension, resulting in shape (x.size(), num_tensors).
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.]]),
 torch.Size([8, 4]))

In [62]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [63]:
y = torch.tensor([1,2,3,4,5])
y,y.shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [64]:
y_stacked = torch.stack([y,y,y,y],dim=0)
y_stacked, y_stacked.shape

(tensor([[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]),
 torch.Size([4, 5]))

In [65]:
x = torch.zeros(2,1,2,1,2)
x,x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

torch.squeeze() - removes all single dimensions from a target tensor. 元素不变，只是删除单一维度

In [66]:
y = torch.squeeze(x)
y,y.size(),y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]),
 torch.Size([2, 2, 2]))

In [67]:
y = torch.squeeze(x,0)
y,y.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [68]:
y = torch.squeeze(x,1)
y,y.shape

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [69]:
# torch.squeeze()
x_reshaped = torch.tensor([[5.,2.,3.,4.,5.,6.,7.,8.,9.]])
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [70]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


torch.permute - rearranges the dimensions of a target tensor in a specified order

In [71]:
import torch
a = torch.randn(2,3,5)
a.size()

torch.Size([2, 3, 5])

In [72]:
b = torch.permute(a,(2,0,1)) # 维度变换，第二个维度5是第一个，第0个维度2放在第2个，第1个维度3放在第3个
b.size()

torch.Size([5, 2, 3])

In [73]:
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1,1->2,2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, wdith]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [74]:
x_original[0,0,0] = 22222

In [75]:
x_permuted[0,0,0]

tensor(22222.)

Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [76]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
x[0][0]

tensor([1, 2, 3])

In [79]:
x[0][1][1]

tensor(5)

In [80]:
x[:,0]

tensor([[1, 2, 3]])

In [81]:
x[:,:,1]

tensor([[2, 5, 8]])

In [82]:
x[:,1,1]

tensor([5])

In [83]:
x[0,0,:]

tensor([1, 2, 3])

In [84]:
x[0,2,2]

tensor(9)

PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library. And because of this, PyTorch has functionality to interact with it.

1. Data in Numpy, want in PyTorch tensor -> torch.from_numpy()
2. PyTorch tensor -> Numpy -> torch.Tensor.numpy()

Numpy 默认数据类型是float64, PyTorch 默认数据类型是float32

In [85]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch,pytorch reflects numpy's default datatyoe of float64 unless specified otherwise.

array,array.dtype,tensor.dtype,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float64,
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
# Change the value of array, what will this do to "tensor"?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
# Change the tensor, what happens to "numpy_tensor"?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducbility (tring to take random out of random) 非常重要！

In short how a neural network learns:
start with random numbers -> tensor operations -> upate random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [89]:
import torch

#create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7989, 0.0315, 0.9083, 0.0687],
        [0.8593, 0.2442, 0.8798, 0.0989],
        [0.7083, 0.6890, 0.0489, 0.0392]])
tensor([[0.2587, 0.2149, 0.0106, 0.1162],
        [0.7339, 0.8958, 0.8552, 0.2781],
        [0.3922, 0.8688, 0.4807, 0.6020]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
#Let's make some random but reproducible tensors
import torch
#Set the random seed

RANDOM_SEED = 42 # 随机数
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # 必须在每个子模块重复设置，否则无法享受一样的seed
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and PyTorch objects on the GPUs(and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

1. Getting a GPU

1.1 Easiest - Use Google Colab for a free GPU

1.2 Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options.

1.3 Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

In [95]:
!nvidia-smi

Mon Aug  3 01:13:31 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8             10W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Check for GPU access with PyTorch

In [92]:
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU pr CPU, it's best practice to setup device agnostic code.

E.g. run on GPU if available, else default to CPU


In [91]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [93]:
torch.cuda.device_count()

1

3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [96]:
#create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [97]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

4. Moving tensors back to the CPU

In [98]:
# If tensor is on GPU, cannot transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [102]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_back_on_cpu.device

(array([1, 2, 3]), 'cpu')

In [103]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

练习题在第31课程